### ISSUE TITLE
Update or enhance sourceset

### ISSUE THREAD

**Issue by schorfES** [moccu/django-ultimatethumb#9]
A nice enhancement would be to pass an already processed sourceset into ultimatethumb again. It's meant to be an update on the given sourceset. An example use can look like this:

```
{% ultimatethumb 'image_sourceset' image '320x0,400x0' %}

...

{% ultimatethumb 'image_sourceset' image_sourceset '320x0,400x0,500x0' retina=True %}
```

This can be used when the reference to the original source image may not be available in the context of the second call.

**Comment by stephrdev** [comment]
Not needed, you can use image_sourceset.0.source
